### ISSUE TITLE
Predicting drug pairs.

### ISSUE THREAD

**Issue by Balackrin** [LabWeng/DDI-GCN#1]
Hello, it's great to see such an excellent job. May I ask how to predict my drug pairs after training the model.

**Comment by LabWeng** [comment]
Dear reader, we created a prediction demo for your question and you can download it from https://wengzq-lab.cn/ddi/predict_demo/Predict_DDI_type_demo.zip and predict your drug pairs in eval_pred_demo.ipynb.

**Comment by Balackrin** [comment]
Thank you very much for your reply, but there seems to be some issues with this webpage and I am unable to open it.

**Comment by LabWeng** [comment]
How about this link http://wengzq-lab.cn/ddi/download.php, then click Predict_DDI_type_demo.
