### ISSUE TITLE
关于冷启动的数据集

### ISSUE THREAD

**Issue by Aaron-Wangyanan** [LabWeng/DDI-GCN#2]
您好，请问您可以分享给我您论文关于S2和S3冷启动任务的二分类数据集吗，我在您提供的数据集下载链接中没有找到该部分。我对您的模型很感兴趣，非常感谢您！

**Comment by LabWeng** [comment]
Thanks for your interest in DDI prediction. You can access to this dataset via http://wengzq-lab.cn/ddi/download.php.
